### ISSUE TITLE
Add Spring EL Processor code from App Launcher Portlet

### ISSUE THREAD

**Issue by codepuppet** [Jasig/portlet-utils#4]

**Comment by codepuppet** [comment]
SSP-187 Add portlet with arbitrary content to demonstrate college-modifiable information portlets

**Comment by jameswennmacher** [comment]
Will add all properties from an optional properties file as ${property['propKey']}, the request parameters as ${requestParam.xxx}, the PortletRequest as ${request.xxx} and user info as ${user}.  Examples
* ${protocol}://${server}:${port}/${contextPath}/view?param=${requestParam.param}
* ${protocol}://${server}:${port}/${contextPath}/view/${requestParam['form.itemId']}
* ${protocol}://${server}:${port}/${contextPath}/view?userId=${user['user.login.id']}
* ${protocol}://${server}:${port}/${contextPath}/view?action=${property['proxy.action.key']}

${server}, ${port}, ${protocol}, and ${contextPath} are also available which are the values for accessing the particular portlet (contextPath in particular is the portlet webapp's context path name).

**Comment by jameswennmacher** [comment]
https://github.com/Jasig/portlet-utils/pull/5
plus
https://github.com/Jasig/portlet-utils/commit/a59b9d5a53220efd377afd842b061c5955f96f07
